OBJS+= $(KERNDIR)/main.o \
       $(KERNDIR)/tty.o \
       $(KERNDIR)/cpu.o \
       $(KERNDIR)/irq.o \
       $(KERNDIR)/panic.o \
       $(KERNDIR)/multiboot.o \
       $(KERNDIR)/memlayout.o \
       $(KERNDIR)/page.o
