OBJS+= $(KERNDIR)/main.o \
       $(KERNDIR)/tty.o \
       $(KERNDIR)/cpu.o \
       $(KERNDIR)/irq.o \
       $(KERNDIR)/panic.o \
       $(KERNDIR)/multiboot.o \
       $(KERNDIR)/page.o \
       $(KERNDIR)/mmap.o \
       $(KERNDIR)/mm.o \
       $(KERNDIR)/vmm.o \
       $(KERNDIR)/buddy.o \
       $(KERNDIR)/list.o
